import os
from pathlib import Path

def create_vault():
    vault_name = "AI_Employee_Vault"
    vault_path = Path(vault_name)
    
    # Core directories from Hackathon Blueprint
    directories = [
        "Inbox",
        "Needs_Action",
        "Plans",
        "Pending_Approval",
        "Approved",
        "Rejected",
        "Done",
        "Logs",
        "Briefings"
    ]
    
    print(f"Initializing {vault_name}...")
    
    # Create directories
    for folder in directories:
        (vault_path / folder).mkdir(parents=True, exist_ok=True)
        print(f"  Created: {folder}")
        
    # Dashboard.md Template (from Blueprint p. 14)
    dashboard_content = """# Monday Morning CEO Briefing

## Executive Summary
*Generated by AI Employee*

## Revenue
- **This Week**: $0.00
- **MTD**: $0.00
- **Trend**: Initializing

## Recent Activity
*No activity logged yet.*

## Pending Approvals
*None.*

---
*Generated by AI Employee v0.1*
"""

    # Company_Handbook.md Template (Rules of Engagement)
    handbook_content = """# Company Handbook - Rules of Engagement

## Core Safety Rules
1. **Always be polite** on WhatsApp and Email.
2. **HITL Required**: Flag any payment over $50 for my approval.
3. **Sensitive Actions**: All social media posts require manual review.
4. **Data Privacy**: Never share personal banking details in plain text.

## Domain Ownership
- **Cloud**: Triage, Drafts, Scheduling.
- **Local**: Approvals, WhatsApp, Payments.
"""

    # Business_Goals.md Template (Blueprint p. 13)
    goals_content = """# Business Goals - Q1 2026

## Objectives
- Monthly Revenue Goal: $10,000
- Client Response Time: < 24 hours

## Key Metrics to Track
| Metric | Target | Current |
|--------|--------|---------|
| Revenue | $10,000 | $0 |
| Response Time | 24h | N/A |

## Active Projects
- [ ] Project A
- [ ] Project B
"""

    # Write core files
    files = {
        "Dashboard.md": dashboard_content,
        "Company_Handbook.md": handbook_content,
        "Business_Goals.md": goals_content
    }
    
    for filename, content in files.items():
        with open(vault_path / filename, "w") as f:
            f.write(content)
        print(f"  Created: {filename}")

    print(f"Vault initialization complete! Ready for Obsidian.")

if __name__ == "__main__":
    create_vault()
